-- Seed de las 14 propiedades actuales del portfolio (generado por scripts/gen-seed.mjs).
-- Ejecutá DESPUÉS de 03_portfolio.sql. estado 'terminado' y publicado true en todas.
-- Se puede correr una sola vez (si lo corrés de nuevo, duplica). Para reiniciar:
--   delete from public.producciones where fuente_seed = true;   -- (ver columna abajo)

alter table public.producciones add column if not exists fuente_seed boolean not null default false;

insert into public.producciones
  (propiedad, titulo, cover, fotos, video_horizontal, video_vertical, tour_url, es_dron, estado, publicado, destacado, orden)
values
  ('Casa Al Lago - Virazón', 'Casa Al Lago - Virazón', '/portfolio-web/Virazon/Portada.jpg', array['/portfolio-web/Virazon/Portada.jpg', '/portfolio-web/Virazon/Foto1.jpg', '/portfolio-web/Virazon/Foto2.jpg', '/portfolio-web/Virazon/Foto3.jpg', '/portfolio-web/Virazon/Foto4.jpg', '/portfolio-web/Virazon/Foto5.jpg']::text[], 'ni3x6uBh2ZA', null, 'https://doormann.viewin360.co/share/collection/7MSq5?logo=0&card=1&info=1&logosize=200&fs=1&vr=0&zoom=1&thumbs=1&inst=es', true, 'terminado', true, true, 0),
  ('Oficina - Puerta Norte', 'Oficina - Puerta Norte', '/portfolio-web/PuertasDelNorte113/Portada.jpg', array['/portfolio-web/PuertasDelNorte113/Portada.jpg', '/portfolio-web/PuertasDelNorte113/Foto1.jpg', '/portfolio-web/PuertasDelNorte113/Foto2.jpg', '/portfolio-web/PuertasDelNorte113/Foto3.jpg']::text[], null, '_I57bl9c1R4', 'https://doormann.viewin360.co/share/collection/7MyD4?logo=1&card=1&info=1&logosize=74&fs=1&vr=0&zoom=1&thumbs=1&inst=es', false, 'terminado', true, false, 1),
  ('Oficina - Puerta Norte', 'Oficina - Puerta Norte', '/portfolio-web/PuertasDelNorte115/Portada.jpg', array['/portfolio-web/PuertasDelNorte115/Portada.jpg', '/portfolio-web/PuertasDelNorte115/Foto1.jpg', '/portfolio-web/PuertasDelNorte115/Foto2.jpg', '/portfolio-web/PuertasDelNorte115/Foto3.jpg']::text[], 'LAEQEEsiOVg', null, 'https://doormann.viewin360.co/share/collection/7Myx8?logo=bWVkaWEvNTk0MjM5LzZhMTgtNDQ2NC00ZjJkLTk0NzUucG5n&info=0&logosize=112&fs=1&vr=0&zoom=1&autopalt=1&thumbs=1&inst=es', false, 'terminado', true, false, 2),
  ('Oficina - Puerta Norte', 'Oficina - Puerta Norte', '/portfolio-web/PuertasDelNorte120/Portada.jpg', array['/portfolio-web/PuertasDelNorte120/Portada.jpg', '/portfolio-web/PuertasDelNorte120/Foto1.jpg', '/portfolio-web/PuertasDelNorte120/Foto2.jpg', '/portfolio-web/PuertasDelNorte120/Foto3.jpg']::text[], 'biaLcqhvHcU', null, null, false, 'terminado', true, false, 3),
  ('Duplex - Olivos', 'Duplex - Olivos', '/portfolio-web/DuplexOlivos/Portada.jpg', array['/portfolio-web/DuplexOlivos/Portada.jpg', '/portfolio-web/DuplexOlivos/Foto1.jpg', '/portfolio-web/DuplexOlivos/Foto2.jpg', '/portfolio-web/DuplexOlivos/Foto3.jpg', '/portfolio-web/DuplexOlivos/Foto4.jpg', '/portfolio-web/DuplexOlivos/Foto5.jpg']::text[], null, 'UjWrEYrJnhU', 'https://kuula.co/share/collection/7Mzql?logo=bWVkaWEvNTk0MjM5LzZhMTgtNDQ2NC00ZjJkLTk0NzUucG5n&info=0&logosize=112&fs=1&vr=0&zoom=1&autorotate=0.08&autop=5&autopalt=1&thumbs=1&inst=es', true, 'terminado', true, false, 4),
  ('Departamento - Terrazas Santa Maria', 'Departamento - Terrazas Santa Maria', '/portfolio-web/Terrazas3erPiso/Portada.jpg', array['/portfolio-web/Terrazas3erPiso/Portada.jpg', '/portfolio-web/Terrazas3erPiso/Foto1.jpg', '/portfolio-web/Terrazas3erPiso/Foto2.jpg', '/portfolio-web/Terrazas3erPiso/Foto3.jpg']::text[], '97-TMfc--qc', null, 'https://kuula.co/share/collection/7MBrd?logo=bWVkaWEvNTk0MjM5LzZhMTgtNDQ2NC00ZjJkLTk0NzUucG5n&info=0&logosize=112&fs=1&vr=0&zoom=1&autorotate=0.08&autop=5&autopalt=1&thumbs=1&inst=', true, 'terminado', true, false, 5),
  ('Casa - Santa Ana a la Laguna', 'Casa - Santa Ana a la Laguna', '/portfolio-web/SantaAna195/Portada.jpg', array['/portfolio-web/SantaAna195/Portada.jpg', '/portfolio-web/SantaAna195/Foto1.jpg', '/portfolio-web/SantaAna195/Foto2.jpg', '/portfolio-web/SantaAna195/Foto3.jpg', '/portfolio-web/SantaAna195/Foto4.jpg']::text[], '6y7ZG6t-P3U', null, 'https://kuula.co/share/collection/71Y1x?logo=bWVkaWEvNTk0MjM5LzZhMTgtNDQ2NC00ZjJkLTk0NzUucG5n&info=0&logosize=112&fs=1&vr=0&zoom=1&autorotate=0.08&autop=5&autopalt=1&thumbs=1&inst=es', true, 'terminado', true, true, 6),
  ('Complejo - Civis', 'Complejo - Civis', '/portfolio-web/Civis/Portada.jpg', array['/portfolio-web/Civis/Portada.jpg', '/portfolio-web/Civis/Foto1.jpg', '/portfolio-web/Civis/Foto2.jpg', '/portfolio-web/Civis/Foto3.jpg', '/portfolio-web/Civis/Foto4.jpg']::text[], '9pBvgShBwUA', null, 'https://doormann.viewin360.co/share/Lvzly?logo=1&card=1&info=1&logosize=74&fs=1&vr=0&zoom=1&thumbs=1&inst=es', true, 'terminado', true, false, 7),
  ('Oficina - Puerta Norte', 'Oficina - Puerta Norte', '/portfolio-web/PuertasDelNorte525/Portada.jpg', array['/portfolio-web/PuertasDelNorte525/Portada.jpg', '/portfolio-web/PuertasDelNorte525/Foto1.jpg', '/portfolio-web/PuertasDelNorte525/Foto2.jpg', '/portfolio-web/PuertasDelNorte525/Foto3.jpg']::text[], 'GhFOs5FXXLA', null, 'https://doormann.viewin360.co/share/collection/7T7sy?logo=1&card=1&info=1&logosize=74&fs=1&vr=0&zoom=1&thumbs=1&inst=es', true, 'terminado', true, false, 8),
  ('Santa Ana — 3 Dormitorios', 'Santa Ana — 3 Dormitorios', '/portfolio-web/SantaAnaPerimetral/Portada.jpg', array['/portfolio-web/SantaAnaPerimetral/Portada.jpg', '/portfolio-web/SantaAnaPerimetral/Foto1.jpg', '/portfolio-web/SantaAnaPerimetral/Foto2.jpg', '/portfolio-web/SantaAnaPerimetral/Foto3.jpg', '/portfolio-web/SantaAnaPerimetral/Foto4.jpg', '/portfolio-web/SantaAnaPerimetral/Foto5.jpg']::text[], null, null, 'https://doormann.viewin360.co/share/collection/7156d?logo=1&card=1&info=1&logosize=74&fs=1&vr=0&zoom=1&thumbs=1&inst=es', true, 'terminado', true, false, 9),
  ('Casa - Carpinchos', 'Casa - Carpinchos', '/portfolio-web/carpinchos352/Portada.jpg', array['/portfolio-web/carpinchos352/Portada.jpg', '/portfolio-web/carpinchos352/Foto1.jpg', '/portfolio-web/carpinchos352/Foto2.jpg', '/portfolio-web/carpinchos352/Foto3.jpg', '/portfolio-web/carpinchos352/Foto4.jpg']::text[], 'sWd10K4Mu_Y', null, 'https://doormann.viewin360.co/share/collection/7T9YC?logo=1&info=0&logosize=112&fs=1&vr=0&zoom=1&autopalt=1&thumbs=1&inst=es', true, 'terminado', true, true, 10),
  ('Lote - Carpinchos', 'Lote - Carpinchos', '/portfolio-web/Lote/Portada.jpg', array['/portfolio-web/Lote/Portada.jpg', '/portfolio-web/Lote/Foto1.jpg', '/portfolio-web/Lote/Foto2.jpg', '/portfolio-web/Lote/Foto3.jpg']::text[], null, 'z5cWA53iPu0', null, true, 'terminado', true, false, 11),
  ('Departamento - Tigre', 'Departamento - Tigre', '/portfolio-web/DeptoTigre/Portada.jpg', array['/portfolio-web/DeptoTigre/Portada.jpg', '/portfolio-web/DeptoTigre/Foto1.jpg', '/portfolio-web/DeptoTigre/Foto2.jpg', '/portfolio-web/DeptoTigre/Foto3.jpg', '/portfolio-web/DeptoTigre/Foto4.jpg']::text[], null, 'SAIckW_n0g0', 'https://doormann.viewin360.co/share/collection/7TqHH?logo=bWVkaWEvNTk0MjM5LzZhMTgtNDQ2NC00ZjJkLTk0NzUucG5n&info=0&logosize=112&fs=1&vr=0&zoom=1&autopalt=1&thumbs=1&inst=es', true, 'terminado', true, false, 12),
  ('Yacht - Construccion', 'Yacht - Construccion', '/portfolio-web/Yacht/Portada.jpg', array['/portfolio-web/Yacht/Portada.jpg', '/portfolio-web/Yacht/Foto1.jpg', '/portfolio-web/Yacht/Foto2.jpg', '/portfolio-web/Yacht/Foto3.jpg']::text[], 'yuDUyYOf9p0', null, null, true, 'terminado', true, false, 13);

update public.producciones set fuente_seed = true where fuente_seed = false and titulo is not null;
