/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#f8cf83',
        'primary-fixed': '#e5e2e1',
        'on-primary-fixed-variant': '#5c5b5b',
        'on-secondary-fixed-variant': '#745716',
        'surface-bright': '#f9f9f9',
        'inverse-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#fbd185',
        'on-primary-fixed': '#403f3f',
        'secondary-container': '#ffdea5',
        'surface-container-low': '#f2f4f4',
        'error-container': '#fe8b70',
        'surface-tint': '#5f5e5e',
        primary: '#5f5e5e',
        'on-error': '#fff7f6',
        'tertiary-dim': '#6b4e0e',
        'inverse-on-surface': '#9c9d9d',
        'on-background': '#2d3435',
        'secondary-fixed': '#ffdea5',
        'on-error-container': '#742410',
        'tertiary-fixed': '#fbd185',
        background: '#f9f9f9',
        secondary: '#785a1a',
        'primary-container': '#e5e2e1',
        'primary-fixed-dim': '#d6d4d3',
        'surface-container-high': '#e4e9ea',
        'on-tertiary-fixed-variant': '#6c500f',
        'on-surface': '#2d3435',
        'on-primary-container': '#525151',
        'tertiary-fixed-dim': '#ecc479',
        'on-primary': '#faf7f6',
        surface: '#f9f9f9',
        'surface-container-highest': '#dde4e5',
        'outline-variant': '#adb3b4',
        outline: '#757c7d',
        tertiary: '#785a1a',
        'primary-dim': '#535252',
        'on-tertiary-fixed': '#4a3400',
        'on-tertiary-container': '#624604',
        'on-secondary': '#fff8f1',
        'error-dim': '#5c1202',
        'surface-variant': '#dde4e5',
        'surface-container': '#ebeeef',
        'on-surface-variant': '#5a6061',
        'on-tertiary': '#fff8f1',
        'secondary-dim': '#6b4e0e',
        error: '#9e422c',
        'on-secondary-fixed': '#543b00',
        'inverse-surface': '#0c0f0f',
        'on-secondary-container': '#694d0c',
        'surface-dim': '#d4dbdd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Montserrat', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
