import { useState } from 'react';
import { useFinance, useOfficialRate } from './finanzas/useFinance';
import FinanceEditor from './finanzas/FinanceEditor';
import { accountStatus, annualSeries, dateLabel, money, MONTHS, METHODS, today, totals, toArs, cents } from './finanzas/model';
import './finanzas/finanzas.css';

const SECTIONS = [['resumen', 'Resumen'], ['movimientos', 'Movimientos'], ['cobros', 'Por cobrar'], ['recurrentes', 'Recurrentes'], ['categorias', 'Categorías']];
function Empty({ children }) { return <div className="fin-empty">{children}</div>; }
function Badge({ children, tone = '' }) { return <span className={`fin-badge ${tone}`}>{children}</span>; }
function Stat({ label, value, tone, hint }) { return <div className={`fin-stat ${tone || ''}`}><p>{label}</p><strong>{money(value)}</strong><span>{hint}</span></div>; }
function exportCsv(rows, categories) {
  const fields = ['Fecha', 'Tipo', 'Estado', 'Descripción', 'Categoría', 'Quién paga', 'Quién recibe', 'Medio', 'Moneda', 'Importe original', 'Cotización', 'Importe ARS'];
  const escape = value => `"${String(value ?? '').replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""')}"`;
  const body = [fields, ...rows.map(r => [r.fecha, r.tipo, r.estado, r.descripcion, categories.find(c => c.id === r.categoria_id)?.nombre, r.pagador, r.receptor, METHODS[r.medio], r.moneda, r.importe, r.cotizacion, r.importe_ars])].map(row => row.map(escape).join(';')).join('\r\n');
  const url = URL.createObjectURL(new Blob(['\ufeff', body], { type: 'text/csv;charset=utf-8;' }));
  const a = document.createElement('a'); a.href = url; a.download = `arko-movimientos-${today()}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export default function Finanzas() {
  const finance = useFinance();
  const rate = useOfficialRate();
  const { movements, categories, accounts, recurring, loading, error, load } = finance;
  const [section, setSection] = useState('resumen');
  const [period, setPeriod] = useState(today().slice(0, 7));
  const [editor, setEditor] = useState(null);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [type, setType] = useState('');
  const [category, setCategory] = useState('');
  const [allDates, setAllDates] = useState(false);
  const [accountFilter, setAccountFilter] = useState('pendientes');
  const year = period.slice(0, 4);
  const monthlyRows = movements.filter(r => r.fecha.startsWith(period));
  const monthly = totals(monthlyRows);
  const annual = totals(movements.filter(r => r.fecha.startsWith(`${year}-`)));
  const series = annualSeries(movements, year);
  const maxBar = Math.max(1, ...series.flatMap(s => [s.entrada, s.salida]));
  const debts = accounts.map(a => ({ ...a, ...accountStatus(a, movements) }));
  const outstanding = debts.reduce((sum, a) => sum + cents(a.remaining), 0) / 100;
  const pending = movements.filter(r => r.estado === 'pendiente' && r.tipo === 'salida').sort((a, b) => (a.vencimiento || a.fecha).localeCompare(b.vencimiento || b.fecha));
  const shown = (allDates ? movements : monthlyRows).filter(r => (!status || status === r.estado) && (!type || type === r.tipo) && (!category || category === r.categoria_id) && `${r.descripcion} ${r.pagador} ${r.receptor}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  const expenses = categories.filter(c => c.tipo === 'salida').map(c => ({ ...c, amount: totals(monthlyRows.filter(r => r.categoria_id === c.id)).salida })).filter(c => c.amount > 0).sort((a, b) => b.amount - a.amount);
  const missingSchema = error && ['PGRST202', 'PGRST205', '42P01', '42883'].includes(error.code);
  const newMovement = () => setEditor({ kind: 'movement' });
  return <div className="finances">
    <div className="fin-heading"><div><p className="fin-eyebrow">ARKO STUDIO / ADMINISTRACIÓN</p><h2>Finanzas</h2><p className="fin-muted">Tu estudio, en números. Todo en pesos argentinos.</p></div><button className="fin-button fin-primary" disabled={loading || !!error} onClick={newMovement}>+ Nuevo movimiento</button></div>
    <div className="fin-rate"><span className="font-bold" aria-hidden="true">USD ↔ ARS</span><div><strong>Dólar oficial · venta</strong> {rate.quote ? `${money(rate.quote.rate)} por USD` : rate.loading ? 'Consultando…' : 'Sin cotización'}<span className="fin-muted">{rate.quote && ` · Actualizado ${new Date(rate.quote.updated).toLocaleString('es-AR')}`}</span>{rate.error && <p className="text-error">{rate.error}</p>}</div><button className="fin-link ml-auto" disabled={rate.loading} onClick={() => rate.refresh()}>Actualizar</button></div>
    <nav className="fin-tabs" aria-label="Secciones de finanzas">{SECTIONS.map(([key, label]) => <button key={key} onClick={() => setSection(key)} aria-current={section === key ? 'page' : undefined} className={section === key ? 'active' : ''}>{label}{key === 'cobros' && debts.some(a => a.remaining > 0) && <span>{debts.filter(a => a.remaining > 0).length}</span>}</button>)}</nav>
    {loading ? <Empty>Cargando tus finanzas…</Empty> : error ? <div className="fin-empty" role="alert"><h3 className="font-bold">{missingSchema ? 'Falta activar la base de finanzas' : 'No se pudieron cargar las finanzas'}</h3><p className="mt-2">{missingSchema ? 'La sección ya está preparada. Falta instalar sus tablas en la base de datos del administrador.' : 'Revisá la conexión e intentá nuevamente. No mostramos totales incompletos.'}</p><button className="fin-button mt-4" onClick={load}>Reintentar</button></div> : <>
      {(section === 'resumen' || section === 'movimientos') && <div className="fin-toolbar"><label className="flex items-center gap-3 text-sm font-medium">Período<input type="month" aria-label="Período" className="input !w-auto" value={period} onChange={e => { if (e.target.value) setPeriod(e.target.value); }} /></label><span className="fin-muted">El balance incluye únicamente pagos confirmados.</span></div>}
      {section === 'resumen' && <>
        <div className="fin-stats"><Stat label="Entrada del mes" value={monthly.entrada} tone="income" hint="Cobros confirmados" /><Stat label="Salida del mes" value={monthly.salida} tone="expense" hint="Gastos pagados" /><Stat label="Balance del mes" value={monthly.balance} tone="balance" hint="Entrada menos salida" /></div>
        <div className="fin-panel mt-5"><div className="fin-heading !mb-5"><div><h3>Balance general de {year}</h3><p className="fin-muted">Enero a diciembre · movimientos registrados</p></div><div className="text-right"><strong className={`text-2xl font-bold ${annual.balance < 0 ? 'text-error' : 'text-on-surface'}`}>{money(annual.balance)}</strong><p className="fin-muted">Entrada {money(annual.entrada)} · Salida {money(annual.salida)}</p></div></div>
          <div className="fin-legend"><span><i className="income" />Entrada</span><span><i className="expense" />Salida</span></div>
          <div className="fin-chart" role="img" aria-label={`Ingresos y gastos mensuales de ${year}. Los valores exactos están en el detalle mensual.`}>{series.map((s, i) => <div key={s.label} className="fin-chart-month"><div className="fin-chart-bars" title={`${s.label}: entrada ${money(s.entrada)}, salida ${money(s.salida)}, balance ${money(s.balance)}`}><div className="income" style={{ height: `${s.entrada / maxBar * 100}%` }} /><div className="expense" style={{ height: `${s.salida / maxBar * 100}%` }} /></div><button onClick={() => setPeriod(`${year}-${String(i + 1).padStart(2, '0')}`)} className={Number(period.slice(5)) === i + 1 ? 'selected' : ''} aria-label={`Ver ${s.label} ${year}`}>{s.label}</button></div>)}</div>
          <details className="mt-4"><summary className="fin-link cursor-pointer">Ver detalle mensual</summary><div className="overflow-x-auto"><table className="fin-table"><thead><tr><th>Mes</th><th>Entrada</th><th>Salida</th><th>Balance</th></tr></thead><tbody>{series.map(s => <tr key={s.label}><td>{s.label}</td><td>{money(s.entrada)}</td><td>{money(s.salida)}</td><td>{money(s.balance)}</td></tr>)}</tbody></table></div></details>
        </div>
        <div className="grid lg:grid-cols-2 gap-5 mt-5"><div className="fin-panel"><div className="fin-heading"><h3>Por cobrar</h3><button className="fin-link" onClick={() => setSection('cobros')}>Ver cuentas →</button></div><strong className="text-2xl font-bold">{money(outstanding)}</strong><p className="fin-muted mt-1">Saldo de todas las cuentas pendientes</p>{debts.filter(a => a.remaining > 0).slice(0, 3).map(a => <div className="fin-list-row" key={a.id}><div><strong>{a.cliente}</strong><p className="fin-muted">{a.descripcion}</p></div><div className="text-right">{money(a.remaining)}<div><Badge tone={a.status === 'Vencido' ? 'expense' : ''}>{a.status}</Badge></div></div></div>)}{!outstanding && <p className="fin-muted mt-5">No hay cobros pendientes.</p>}</div>
          <div className="fin-panel"><div className="fin-heading"><h3>Gastos por categoría</h3><span className="fin-muted">{MONTHS[Number(period.slice(5)) - 1]}</span></div>{expenses.length ? expenses.slice(0, 6).map(c => <div className="mb-4" key={c.id}><div className="flex justify-between gap-3 text-sm mb-2"><span>{c.nombre}</span><strong>{money(c.amount)}</strong></div><div className="fin-progress"><div style={{ width: `${c.amount / monthly.salida * 100}%` }} /></div></div>) : <p className="fin-muted">Los gastos confirmados aparecerán acá.</p>}</div></div>
        <div className="fin-panel mt-5"><div className="fin-heading"><div><h3>Gastos pendientes</h3><p className="fin-muted">Vencimientos generados hasta fin del mes actual · no afectan el balance</p></div><Badge>{pending.length} pendientes</Badge></div>{pending.length ? pending.slice(0, 5).map(r => <div className="fin-list-row" key={r.id}><div><strong>{r.descripcion}</strong><p className="fin-muted">{dateLabel(r.vencimiento || r.fecha)} · {r.receptor}{(r.vencimiento || r.fecha) < today() ? ' · Vencido' : ''}</p></div><div className="text-right"><strong>{r.moneda === 'USD' ? `USD ${r.importe}` : money(r.importe)}</strong><button className="fin-link block mt-1" onClick={() => setEditor({ kind: 'movement', value: r, confirmPayment: true })}>Confirmar pago</button></div></div>) : <p className="fin-muted">Estás al día con los gastos registrados.</p>}{pending.length > 5 && <button className="fin-link mt-3" onClick={() => { setSection('movimientos'); setStatus('pendiente'); setType('salida'); setAllDates(true); }}>Ver todos los pendientes →</button>}</div>
      </>}
      {section === 'movimientos' && <>
        <div className="fin-filters"><input className="input" aria-label="Buscar movimientos" placeholder="Buscar descripción o persona…" value={search} onChange={e => setSearch(e.target.value)} /><select className="input" aria-label="Tipo de movimiento" value={type} onChange={e => setType(e.target.value)}><option value="">Entradas y salidas</option><option value="entrada">Entrada</option><option value="salida">Salida</option></select><select className="input" aria-label="Estado" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos los estados</option><option value="pagado">Confirmados</option><option value="pendiente">Pendientes</option><option value="anulado">Anulados</option></select><select className="input" aria-label="Categoría" value={category} onChange={e => setCategory(e.target.value)}><option value="">Todas las categorías</option>{categories.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></div>
        <div className="flex justify-between gap-3 my-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={allDates} onChange={e => setAllDates(e.target.checked)} />Todos los períodos</label><button className="fin-link" disabled={!shown.length} onClick={() => exportCsv(shown, categories)}>Exportar CSV ({shown.length})</button></div>
        {!shown.length ? <Empty>No hay movimientos para estos filtros. Podés cargar pagos de cualquier mes.</Empty> : <div className="overflow-x-auto"><table className="fin-table"><thead><tr><th>Fecha / estado</th><th>Descripción / categoría</th><th>Quién paga → recibe</th><th>Importe</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{shown.map(r => <tr key={r.id}><td className="whitespace-nowrap">{dateLabel(r.fecha)}<div><Badge tone={r.estado === 'pagado' ? 'income' : r.estado === 'anulado' ? '' : 'pending'}>{r.estado === 'pagado' ? 'Confirmado' : r.estado === 'anulado' ? 'Anulado' : 'Pendiente'}</Badge></div></td><td><strong>{r.descripcion}</strong><p className="fin-muted">{categories.find(c => c.id === r.categoria_id)?.nombre}</p></td><td>{r.pagador} → {r.receptor}<p className="fin-muted">{METHODS[r.medio]}</p></td><td className="whitespace-nowrap"><strong className={r.tipo === 'entrada' ? 'text-emerald-700' : 'text-error'}>{r.tipo === 'entrada' ? '+' : '−'} {r.importe_ars === null ? `USD ${r.importe}` : money(r.importe_ars)}</strong>{r.moneda === 'USD' && <p className="fin-muted">USD {r.importe} {r.cotizacion ? `× ${r.cotizacion}` : '· a convertir al pagar'}</p>}</td><td className="text-right whitespace-nowrap">{r.estado === 'pendiente' && <button className="fin-link block mb-2" onClick={() => setEditor({ kind: 'movement', value: r, confirmPayment: true })}>Confirmar pago</button>}<button className="fin-link" onClick={() => setEditor({ kind: 'movement', value: r })}>Editar</button></td></tr>)}</tbody></table></div>}
      </>}
      {section === 'cobros' && <><div className="fin-heading"><div><h3>Cuentas por cobrar</h3><p className="fin-muted">50% de anticipo, 50% al entregar. También podés registrar otros importes.</p></div><button className="fin-button" onClick={() => setEditor({ kind: 'account' })}>+ Nueva cuenta</button></div><div className="fin-toolbar"><p>Pendiente total <strong className="ml-2">{money(outstanding)}</strong></p><select className="input !w-auto" aria-label="Filtrar cuentas" value={accountFilter} onChange={e => setAccountFilter(e.target.value)}><option value="pendientes">Con saldo pendiente</option><option value="todas">Todas las cuentas</option><option value="pagadas">Pagadas</option></select></div>
        {debts.filter(a => accountFilter === 'todas' || (accountFilter === 'pagadas' ? a.remaining === 0 : a.remaining > 0)).length === 0 ? <Empty>No hay cuentas para mostrar. Creá una para llevar el anticipo y el saldo de un cliente.</Empty> : <div className="space-y-4">{debts.filter(a => accountFilter === 'todas' || (accountFilter === 'pagadas' ? a.remaining === 0 : a.remaining > 0)).sort((a, b) => (a.vencimiento || '9999').localeCompare(b.vencimiento || '9999')).map(a => <div className="fin-panel" key={a.id}><div className="fin-heading"><div><h3>{a.cliente}</h3><p className="fin-muted">{a.descripcion}{a.vencimiento && ` · Vence ${dateLabel(a.vencimiento)}`}</p></div><Badge tone={a.status === 'Pagado' ? 'income' : a.status === 'Vencido' ? 'expense' : 'pending'}>{a.status}</Badge></div><div className="grid grid-cols-3 gap-3 text-sm mb-3"><div className="fin-muted">Total<strong className="block text-on-surface mt-1">{money(a.total)}</strong></div><div className="fin-muted">Cobrado<strong className="block text-emerald-700 mt-1">{money(a.paid)}</strong></div><div className="fin-muted">Pendiente<strong className="block text-on-surface mt-1">{money(a.remaining)}</strong></div></div><div className="fin-progress"><div style={{ width: `${Math.min(100, a.paid / a.total * 100)}%` }} /></div><div className="flex justify-between items-center gap-3 mt-4"><button className="fin-link" onClick={() => setEditor({ kind: 'account', value: a })}>Editar cuenta</button>{a.remaining > 0 && <button className="fin-button fin-primary" onClick={() => setEditor({ kind: 'movement', account: a })}>{a.paid === 0 ? 'Registrar anticipo' : 'Registrar pago'}</button>}</div><details className="mt-4"><summary className="fin-link cursor-pointer">Historial de pagos</summary>{movements.filter(r => r.cobro_id === a.id).map(r => <div key={r.id} className="fin-list-row"><span>{dateLabel(r.fecha)} · {METHODS[r.medio]} · {r.estado}</span><button className="fin-link" onClick={() => setEditor({ kind: 'movement', value: r })}>{money(r.importe_ars)} · Editar</button></div>)}{!movements.some(r => r.cobro_id === a.id) && <p className="fin-muted mt-2">Todavía no hay pagos registrados.</p>}</details></div>)}</div>}
      </>}
      {section === 'recurrentes' && <><div className="fin-heading"><div><h3>Gastos recurrentes</h3><p className="fin-muted">Suscripciones, pagos anuales y compras en cuotas.</p></div><button className="fin-button" onClick={() => setEditor({ kind: 'recurring' })}>+ Nuevo recurrente</button></div><p className="fin-note mb-5">Al abrir Finanzas se generan los vencimientos hasta fin del mes actual, incluidos los meses anteriores. Confirmá cada pago desde Movimientos o el resumen.</p>{!recurring.length ? <Empty>Agregá tu primera suscripción para tener sus vencimientos a mano.</Empty> : <div className="overflow-x-auto"><table className="fin-table"><thead><tr><th>Gasto</th><th>Importe por período</th><th>Calendario</th><th>Estado</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{recurring.map(r => <tr key={r.id}><td><strong>{r.descripcion}</strong><p className="fin-muted">{r.receptor}</p></td><td>{r.moneda === 'USD' ? `USD ${r.importe}` : money(r.importe)}{r.moneda === 'USD' && <p className="fin-muted">{rate.quote ? `≈ ${money(toArs(r.importe, 'USD', rate.quote.rate))} hoy` : 'Sin cotización'}</p>}</td><td>{r.frecuencia === 'mensual' ? 'Mensual' : 'Anual'} · desde {dateLabel(r.inicio)}<p className="fin-muted">{r.cuotas ? `${r.cuotas} cuotas` : 'Sin límite de cuotas'}{r.fin && ` · hasta ${dateLabel(r.fin)}`}</p></td><td><Badge>{!r.activa ? 'Pausado' : (r.fin && r.fin < today()) || (r.cuotas && movements.filter(m => m.recurrente_id === r.id).length >= r.cuotas) ? 'Finalizado' : 'Activo'}</Badge></td><td><button className="fin-link" onClick={() => setEditor({ kind: 'recurring', value: r })}>Editar</button></td></tr>)}</tbody></table></div>}</>}
      {section === 'categorias' && <><div className="fin-heading"><div><h3>Tus categorías</h3><p className="fin-muted">Adaptalas a tu estudio. Archivar una categoría conserva sus movimientos.</p></div><button className="fin-button" onClick={() => setEditor({ kind: 'category' })}>+ Nueva categoría</button></div><div className="grid md:grid-cols-2 gap-5">{['entrada', 'salida'].map(t => <div className="fin-panel" key={t}><h3>{t === 'entrada' ? 'Entradas' : 'Salidas'}</h3>{categories.filter(c => c.tipo === t).map(c => <div className="fin-list-row" key={c.id}><span>{c.nombre}{!c.activa && <span className="fin-muted"> · Archivada</span>}</span><button className="fin-link" onClick={() => setEditor({ kind: 'category', value: c })}>Editar</button></div>)}</div>)}</div></>}
      <p className="fin-footer">Control interno · ARS · <a href="https://dolarapi.com/docs/argentina/operations/get-dolar-oficial" target="_blank" rel="noreferrer">Cotización de referencia: DolarApi</a></p>
    </>}
    {editor && <FinanceEditor editor={editor} categories={categories} movements={movements} quote={rate.quote} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); load(); }} />}
  </div>;
}
